# Word Embeddings with Keras Embedding Layer

## Problem Statement
Learn how to convert text sequences into dense vector representations using the Keras Embedding layer. This notebook demonstrates:
1. **One-Hot Encoding**: Convert words into one-hot vectors
2. **Padding**: Standardize sequence lengths
3. **Embedding Layer**: Transform integer sequences into dense embedding vectors
4. **Output**: Generate embedding representations for text data that can be used in neural networks

## Objective
Understand how word embeddings work as an alternative to sparse one-hot representations for NLP tasks.

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
sentences = ['the cat sat on the mat', 
             'the dog sat on the log', 
             'the cat sat on the log',
             'understand meaning of words',
             'Moveie is a great way to understand the world']
sentences

['the cat sat on the mat',
 'the dog sat on the log',
 'the cat sat on the log',
 'understand meaning of words',
 'Moveie is a great way to understand the world']

In [14]:
# Define vocabulary size
vocab_size = 10000

In [4]:
## One-hot representation
onehot_repr = [one_hot(words, vocab_size) for words in sentences]
onehot_repr

[[8338, 7483, 1398, 5761, 8338, 3405],
 [8338, 4432, 1398, 5761, 8338, 9952],
 [8338, 7483, 1398, 5761, 8338, 9952],
 [2045, 8299, 3250, 1242],
 [9253, 6060, 424, 2294, 888, 6154, 2045, 8338, 9989]]

In [10]:
# word embedding representation
from tensorflow.keras.layers import Embedding
import numpy as np
sent_length = 10
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 8338, 7483, 1398, 5761, 8338, 3405],
       [   0,    0,    0,    0, 8338, 4432, 1398, 5761, 8338, 9952],
       [   0,    0,    0,    0, 8338, 7483, 1398, 5761, 8338, 9952],
       [   0,    0,    0,    0,    0,    0, 2045, 8299, 3250, 1242],
       [   0, 9253, 6060,  424, 2294,  888, 6154, 2045, 8338, 9989]],
      dtype=int32)

In [15]:
# feature dimension
dim = 10
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
output = model.predict(embedded_docs)
print(f"Output shape: {output.shape}")
output

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
Output shape: (5, 10, 10)


array([[[-4.74655889e-02, -9.11288336e-03, -2.66984589e-02,
          1.55339278e-02, -1.63766742e-02, -3.10827252e-02,
          3.29845883e-02, -2.46809963e-02,  3.08968090e-02,
         -1.83930509e-02],
        [-4.74655889e-02, -9.11288336e-03, -2.66984589e-02,
          1.55339278e-02, -1.63766742e-02, -3.10827252e-02,
          3.29845883e-02, -2.46809963e-02,  3.08968090e-02,
         -1.83930509e-02],
        [-4.74655889e-02, -9.11288336e-03, -2.66984589e-02,
          1.55339278e-02, -1.63766742e-02, -3.10827252e-02,
          3.29845883e-02, -2.46809963e-02,  3.08968090e-02,
         -1.83930509e-02],
        [-4.74655889e-02, -9.11288336e-03, -2.66984589e-02,
          1.55339278e-02, -1.63766742e-02, -3.10827252e-02,
          3.29845883e-02, -2.46809963e-02,  3.08968090e-02,
         -1.83930509e-02],
        [ 3.56220640e-02, -4.69405055e-02,  4.98986579e-02,
         -3.79593372e-02, -3.50484028e-02, -4.06361818e-02,
         -2.60768067e-02, -4.63866480e-02,  4.345004

In [19]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[-0.04746559, -0.00911288, -0.02669846,  0.01553393,
         -0.01637667, -0.03108273,  0.03298459, -0.024681  ,
          0.03089681, -0.01839305],
        [-0.04746559, -0.00911288, -0.02669846,  0.01553393,
         -0.01637667, -0.03108273,  0.03298459, -0.024681  ,
          0.03089681, -0.01839305],
        [-0.04746559, -0.00911288, -0.02669846,  0.01553393,
         -0.01637667, -0.03108273,  0.03298459, -0.024681  ,
          0.03089681, -0.01839305],
        [-0.04746559, -0.00911288, -0.02669846,  0.01553393,
         -0.01637667, -0.03108273,  0.03298459, -0.024681  ,
          0.03089681, -0.01839305],
        [ 0.03562206, -0.04694051,  0.04989866, -0.03795934,
         -0.0350484 , -0.04063618, -0.02607681, -0.04638665,
          0.04345005, -0.01451593],
        [-0.0136894 ,  0.02983255, -0.01878829,  0.03695707,
          0.02510569, -0.01020722,  0.00520306,  0.00551675,
          0.03662337,  0.01557142],
        [-0.01752441,  0.01421523,  0.04476991, -0.0