**Word2Vec**


Implementing this technique using google model - word2vec-google-news-300
This is pre-trained model



In [4]:
! pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 85.3 MB/s eta 0:00:00


In [5]:
import gensim

In [6]:
from gensim.models import KeyedVectors, Word2Vec

In [6]:
## Reference - https://stackoverflow.com/questions/42094180/spacy-how-to-load-google-news-word2vec-vectors
## https://huggingface.co/fse/word2vec-google-news-300

In [7]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [8]:
vek_king = wv['King']
vek_king

array([-0.00350952,  0.01623535, -0.08154297,  0.12792969,  0.11230469,
       -0.00534058,  0.03063965,  0.04931641,  0.22070312,  0.07373047,
       -0.13769531,  0.16210938,  0.02148438, -0.09375   , -0.12792969,
       -0.12402344, -0.11132812,  0.11816406, -0.07861328,  0.25390625,
        0.01794434,  0.14160156,  0.0612793 , -0.08691406,  0.07763672,
        0.05175781, -0.24609375, -0.17578125,  0.14746094,  0.06640625,
       -0.03833008, -0.09033203, -0.07226562,  0.09375   , -0.18847656,
        0.06347656,  0.24121094,  0.00714111, -0.30273438, -0.02478027,
       -0.09619141, -0.30859375, -0.06054688,  0.22167969,  0.07763672,
        0.05834961,  0.15527344, -0.13476562, -0.00341797, -0.13964844,
       -0.02905273,  0.03833008, -0.15332031, -0.20996094,  0.21679688,
        0.01171875, -0.078125  ,  0.00402832, -0.23535156, -0.10400391,
        0.08837891,  0.25976562,  0.02709961,  0.01123047,  0.12988281,
       -0.11914062, -0.07861328, -0.04736328, -0.06591797,  0.07

In [13]:
vek_king.shape

(300,)

In [28]:
wv['modi']

array([-9.61914062e-02,  8.93554688e-02,  1.66015625e-01,  2.24609375e-01,
       -2.10937500e-01,  9.81445312e-02,  1.26953125e-01, -3.85742188e-02,
       -2.48046875e-01,  7.81250000e-02, -1.79687500e-01, -2.51953125e-01,
       -2.63671875e-01, -8.05664062e-02, -1.45507812e-01,  4.02343750e-01,
        3.28125000e-01, -1.06445312e-01, -6.34765625e-02, -1.32812500e-01,
        8.34960938e-02, -1.89453125e-01,  4.06250000e-01, -9.08203125e-02,
       -1.43554688e-01, -9.91210938e-02, -2.00195312e-01, -7.51953125e-02,
        1.33789062e-01, -8.00781250e-02, -3.34472656e-02,  6.59179688e-02,
       -2.18200684e-03,  3.75976562e-02, -2.49023438e-01,  2.50000000e-01,
       -7.71484375e-02,  8.98437500e-02,  9.71679688e-02, -7.71484375e-02,
        2.77099609e-02,  3.94821167e-04,  2.71484375e-01,  2.21679688e-01,
       -3.14941406e-02, -4.53125000e-01, -4.46777344e-02, -1.32812500e-01,
       -2.29492188e-01,  4.78515625e-02, -1.24023438e-01,  1.04492188e-01,
        1.45507812e-01,  

In [18]:
#Here similarity() score higher the value more similarity to other word and lower the value means less similarity
wv.similarity("modi","hockey")

np.float32(0.074368015)

In [23]:
wv.cosine_similarities(wv['apple'], wv['fruit', 'banana','phone','chemical'])

array([0.64101464, 0.53184056, 0.1343919 , 0.07195607], dtype=float32)

In [24]:
# distance() is used to find the how close the other word is if score is lesser then it closer and if score is more its farther
wv.distance('apple','fruit')

np.float32(0.3589853)

In [27]:
wv.distances('apple','fruit')

array([0.87069464, 0.8628918 , 0.81426024, 0.8347549 , 0.79155207],
      dtype=float32)

In [34]:
v=wv['king']+wv['queen']
v

array([ 0.13122559, -0.11376953, -0.06072998,  0.2631836 ,  0.10620117,
       -0.125     ,  0.04052734, -0.41503906, -0.1459961 ,  0.4189453 ,
       -0.3178711 , -0.68359375, -0.07373047, -0.02571869, -0.03515625,
       -0.05712891,  0.10742188, -0.04165649,  0.11230469,  0.22314453,
        0.32714844,  0.24951172, -0.17675781,  0.01806641,  0.1665039 ,
       -0.22998047, -0.5605469 ,  0.15161133,  0.53027344, -0.19812012,
       -0.05175781, -0.0690918 ,  0.04199219,  0.61328125, -0.6777344 ,
       -0.04785156,  0.1352539 ,  0.26953125, -0.02441406,  0.3564453 ,
        0.24560547, -0.64746094,  0.5527344 ,  0.11486816,  0.5175781 ,
       -0.13671875, -0.11398315,  0.17871094,  0.1015625 ,  0.28289795,
       -0.18005371,  0.25683594, -0.20678711, -0.0111084 , -0.32617188,
       -0.05674744, -0.48828125, -0.22973633,  0.15722656, -0.11499023,
        0.3203125 ,  0.7265625 , -0.04022217,  0.26171875,  0.27441406,
       -0.40722656, -0.11199951,  0.00683594, -0.30664062,  0.40

In [35]:
wv.most_similar([v])

[('queen', 0.9126338362693787),
 ('king', 0.904472827911377),
 ('monarch', 0.704138457775116),
 ('kings', 0.6757685542106628),
 ('princess', 0.6753551363945007),
 ('queens', 0.6710299253463745),
 ('prince', 0.6427620649337769),
 ('royal', 0.598995566368103),
 ('princes', 0.5936275720596313),
 ('crown_prince', 0.5886804461479187)]